logging:
  level:
    ROOT: INFO
    org.example: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    initialize: true
    url: jdbc:h2:file:~/test
    username: sa
    password: